require "config.autocmd"
require "config.globals"
require "config.keymap"
require "config.lsp"
require "config.options"
require "config.theme"

require "plugins.files"
require "plugins.style"
-- require "plugins.treesitter"
require "plugins.markdown"
