# Options
setopt HIST_SAVE_NO_DUPS # No duplicates in zsh history

# ZSH setup
source $ZDOTDIR/.zshenv
source $ZDOTDIR/aliases

# bun completions
[ -s "/Users/sqibo/.bun/_bun" ] && source "/Users/sqibo/.bun/_bun"

# NVM completions
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# Zoxide - smarter cd command
eval "$(zoxide init zsh)"

# Start
uwufetch -wr  # display and reads cached info add -i to use images

# Prompt (fallback — starship overrides this if loaded)
PROMPT='%f%K{cyan}%F{black} %~ %f%k%F{cyan}%f '
RPROMPT=' %F{blue}%K{blue}%F{black} %n@%m %f%k%F{blue}'

# Local overrides (auto-generated by tools like pipx, bun, etc.)
[ -f "$ZDOTDIR/.zshrc.local" ] && source "$ZDOTDIR/.zshrc.local"
