# Kitty terminal — only non-default settings
# Run `kitty --debug-config` to see all effective values

font_family     jetbrains-mono
disable_ligatures never
enable_audio_bell no
remember_window_size  yes
window_border_width 10pt
hide_window_decorations yes
confirm_os_window_close 0
background_opacity 0.75
background_blur 16
dynamic_background_opacity yes
include current-theme.conf
map shift+enter send_text all \e\r
